"""empty message

Revision ID: 524e61aca2fb
Revises: 19e3018d0fa6
Create Date: 2023-07-27 15:26:33.912861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524e61aca2fb'
down_revision = '19e3018d0fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###
