"""empty message

Revision ID: 9a12faa77617
Revises: de8e92e08554
Create Date: 2023-07-31 11:08:43.277588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a12faa77617'
down_revision = 'de8e92e08554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bucket_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bucket_list', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
